const utils = require('./../utils');

const generator = require('./generator/generator.js');

module.exports = {
    WelcomeCommand: function (client, args, receivedCommand) {
        var name = undefined;
        if (args.length > 0) {
            name = _get_user_from_mention(client, args[0])
        }
        console.log(name);

        var rand_top_4_text = ["TOP 4 FAVOURITE POWER METAL BANDS", "TOP 4 FAVOURITE PM BANDS", "TOP 4 POWER METAL BANDS", "TOP 4 PM BANDS"]

        var top_4_feed = `
            HOWEVER THEY ASK FOR YOUR TOP4 OF ALL TIME TO COMPLETE THE RIDDLE!
            CARE TO SHARE YOUR TOP4.
            WE LIKE TO ASK NEW PEOPLE FOR THEIR TOP4.
            WE ASK THEM FOR THEIR TOP4.
            WHAT ARE YOUR TOP4?
            YOU MUST DECLARE YOUR TOP4 WITHOUT DELAY!
            PRAY TELL US YOUR TOP4.
            I'LL JUST SKIP TO THE PART WHERE I ASK YOU FOR YOUR TOP4 WITH SINGERS NAMED STEVE.
            PLEASE, BESTOW UPON US YOUR TOP4!
            PLEASE TELL US YOUR TOP4.
            PLEASE, BESTOW UPON US YOUR TOP4!
            TO ASK THEM FOR THEIR TOP4.
            TELL US YOUR TOP4 OR FACE... SOMETHING IDK.
            CARE TO SHARE YOUR TOP4?
            WE LIKE TO ASK NEW PEOPLE TO SHARE THEIR TOP4 SO WE CAN OFFER HELPFUL SUGGESTIONS ABOUT OTHER THINGS THEY MIGHT LIKE.
            REGALE US YOUR TOP4.
            HOW ABOUT YOU SHARE YOUR TOP4 WITH US?
            CAN WE HAVE YOUR TOP4?
            CRY HAVOC AND LET LOOSE UPON US YOUR TOP4.
            PLEASE DISREGARD THE NSFW CHANNEL AND GRACE US WITH YOUR TOP4.
            WHAT ARE YOUR TOP4.
            WHICH IS WHY WE LIKE TO ASK NEW PEOPLE FOR THEIR TOP4.
            WHAT ARE YOUR TOP4?
            INSTEAD I'LL JUST ASK YOU TO SHARE YOUR TOP4.
            PLEASE TELL THE GROUP YOUR TOP4!
            WHAT ARE YOUR TOP4?
            GRANT US THE KNOWLEDGE OF YOUR TOP4.
            REGALE US WITH THE EPIC SAGA OF YOUR TOP4!
            PLEASE TELL US YOUR TOP4 SO WE CAN RECOMMEND BETTER ONES!
            PRAY TELL YOUR TOP4 SO WE CAN RECOMMEND SOMETHING BETTER.
            WHAT ARE YOUR TOP4 AND WHY ARE THEY ALL WARKINGS?
            PLEASE TELL THE GROUP YOUR TOP4 AND WE WILL THEN RESULT TO JUDGE YOU.
            ENLIGHTEN US WITH YOUR TOP4 SO WE TOO MAY STAND IN AWE OF THEIR MUSIC. 
            BLESS US WITH YOUR TOP4 SO WE CAN RECOMMEND YOU GLORIOUS MUSIC!
            YOUR ONLY MISSION IS TO PROVIDE US YOUR TOP4
            UNFURL THE EPIC TALE OF YOUR TOP4.
            PROVE YOUR WORTHINESS BY LISTING YOUR TOP4 IN ANY ORDER YOU DEEM FIT.
            TELL US OF YOUR TOP4 SO WE TOO CAN JUDGE YOUR WORTHINESS.
            CARE TO SHARE YOUR TOP4?
            MAKE HASTE AND INFORM YOUR FELLOW WARRIORS OF YOUR TOP4 SO THAT WE MAY DEEM YOU HAVE ALWAYS BEEN WORTHY.
            ENLIGHTEN US TO THE TOP4 THAT AWAIT ME!
            I AM ASKING WHAT YOUR TOP4 ARE.
            YOU WILL FIND A HORDE OF METALHEADS ASKING FOR YOUR TOP4!
            YOU MUST FIGHT IT OUT TO THE DEATH BY EACH NAMING YOUR TOP4
            NAME YOUR TOP4 WITHOUT DOUBT OR BE CAST FROM THIS REALM FOREVER!
            PLEASE DISTRACT US BY SHARING YOUR TOP4.
            CAN YOU TELL US HOW TO GET TO SESAME STREET YOUR TOP4?
            MAKE HASTE AND REGALE US THE TALE OF YOUR TOP4.
            TOP4 OR I'LL PUNCH A CAT!
            BLESS US WITH YOUR TOP4 SO THAT WE MAY KNOW YOUR TRUE STEEL HEART!
            BESTOW UPON US THE KNOWLEDGE OF YOUR TOP4.
            SO TELL US WARRIOR OF YOUR TOP4 SO WE MAY SHIT ON YOUR TASTE TOO AND YOU MAY BECOME ONE OF US.
            DURING YOUR PITIFUL LIFE WHICH TOP4 DID YOU PERFORM YOUR PATHETIC DEEDS TO?
            NAME YOUR TOP4.
            YOU MUST DISCLOSE YOUR TOP4!
            WHAT ATE YOUR TOP4.
            NAME YOUR TOP4.
            WHAT ARE YOUR TOP4 OF STEEL TO PROVE THE QUALITY OF YOUR FORGING?
            RECITE YOUR TOP4 SO THAT WE MAY GATHER THEIR POWER TO AVERT DISASTER!
            SHARE WITH US YOUR TOP4 IN WHATEVER ORDER YOU SO CHOOSE SO WE TOO MAY KNOW YOUR TASTES.
        `;

        var result = generator.generate({
            wordsCount: _rand_range(75, 120),
            sampleSize: _rand_range(4, 6),
            source: `
                HAIL BRAVE WARRIOR OF STEEL, THE ORACLES SPOKE OF YOUR PASSING! THE RUNES HAVE BEEN DECIPHERED AND DEPICT A MESSAGE OF TRUE STEEL, HOWEVER THEY ASK FOR YOUR TOP4 OF ALL TIME TO COMPLETE THE RIDDLE!
                HAIL AND WELCOME TO VALHALLA WHERE WE ARE THE ABYSS THAT NIETZCHE TRIED TO WARN EVERYONE ABOUT. GOOD TASTE AND/OR TAKES GAZE INTO US AND TRULY, SPECTACULARLY, AWFULEXCELLENT TAKES COME OUT.SPEAKING OF WHICH, CARE TO SHARE YOUR TOP4.
                WELCOME TO VALHALLA WHERE WE HAVE BOTH HEROES AND. AS DAN HINTED AT IN HIS SUBTLE AND UNDERSTATED FASHION, WE LIKE TO ASK NEW PEOPLE FOR THEIR TOP4. SOMETIMES WE EVEN GET RESPONSES AND HARDLY KNOW WHAT TO DO WITH OURSELVES.
                HAIL TO THE WHOSE COMING WAS FORETOLD IN THE ANNALS OF THE SKALDS. NOT THE MAIN ANNALS, MIND YOU, BUT THE SUB-SUB-SUB ONES. THE ANNALTATIONS, IF YOU WILL. ANYWAY. WELCOME TO VALHALLA WHERE WE LIKE TO ASK NEW PEOPLE FOR THEIR TOP4. MOSTLY TO BREAK THE ICE, BUT ALSO TO REMIND THE REGULARS THAT THIS IS, NOMINALLY, A PLACE TO TALK ABOUT POWER METAL INSTEAD OF SKA OR GLOOMHAVEN OR WHATEVER. BUT I DIGRESS. WHAT ARE YOUR TOP4?
                HAIL FELLOW SOJOURNER ALONG THE HALLS OF POWER METAL DECAY. TO PASS THROUGH THE GATE TO THE FEASTING HALL OF RIFFS AND BEER, YOU MUST DECLARE YOUR TOP4 WITHOUT DELAY!
                HAIL AND WELCOME TO VALHALLA WHERE WE CELEBRATE THE GLORY OF HANSI KÜRSCH! PRAISE BE! PRAY TELL US YOUR TOP4.
                HAIL AND WELCOME TO VALHALLA. THIS IS WHERE I'D NORMALLY TRY TO MAKE SOME DUMB JOKE BASED ON NORSE MYTHOLOGYAND YOUR USERNAME, BUT MY BRAIN IS BUSY WITH AVOIDING DOING REAL WORK SO INSTEAD I'LL JUST SKIP TO THE PART WHERE I ASK YOU FOR YOUR TOP4 WITH SINGERS NAMED STEVE.
                HAIL AND WELCOME, MIGHTY , COME TO US IN A QUEST FOR WISDOM AND GLORY! SO WE MAY BEST ADVISE YOU ON YOUR JOURNEY, PLEASE, BESTOW UPON US YOUR TOP4!
                HAIL AND WELCOME TO VALHALLA WHERE YOUR COMING HAS BEEN FORETOLD! WHERE THE GODS AND DEITIES TOLD US THAT YOUR ARRIVAL WOULD ALTER THE FACE OF THE EARTH FOREVER! IN VIEW OF THIS GREAT HONOR, PLEASE TELL US YOUR TOP4.
                THE THUNDER RUMBLES... AS FORETOLD BY PROPHECIES OF OLD, THE GREAT WARRIOR ARRIVES AT THE HALLS OF VALHALLA! PLEASE, BESTOW UPON US YOUR TOP4!
                HAIL AND WELCOME TO VALHALLA WHERE WE TALK ABOUT MELODEATH, ATMOBLACK, FOLK AND EUROBEAT BUT NEVER POWER METAL. PRAY TELL US YOUR TOP4.
                HAIL AND WELCOME TO VALHALLA. EVERY TIME SOMEONE NEW JOINS WE LIKE TO PAUSE THE SHITTING ON EVERYTHING TO ASK THEM FOR THEIR TOP4 SO WE CAN SHIT ON THEIR TASTE PROPERLY, TOO.
                HAIL AND KILL NEW BARD NOW THAT YOU'RE HERE, TELL US YOUR TOP4 OR FACE... SOMETHING IDK.
                HAIL AND WELCOME TO VALHALLA WHERE THE TRVE WARRIORS NEVER GET A HANGOVER. PRAY TELL US YOUR TOP4.
                WELCOME TO VALHALLA! I HAVE TO ADMIT THAT I'VE ONLY EVER SEEN THE NORMAL SIZE OF MARZIPAN PIG BEFORE SO THIS IS PRETTY EXCITING. BUT BEFORE WE GET THE FORKS AND KNIVES OUT, CARE TO SHARE YOUR TOP4?
                HAIL AND WELL MET! WELCOME TO VALHALLA WHERE THE HORSES HAVE EIGHT LEGS AND TERRIBLE TASTE AND THE APPLES DON'T GIVE YOU YOUTH, BUT DO GET YOU USED TO YELLING AT KIDS TO GET OFF YOUR LAWN AND HOW MUCH BETTER POWER METAL WAS IN THE OLD DAYS BEFORE THESE NEWFANGLED SYNTHS WITH THEIR BLEEPS AND BLOOPS SHOWED UP AND STARTED SINGING ABOUT FANTASY THINGS THAT WERE PUBLISHED AFTER 1970, BUT I DIGRESS. WE LIKE TO ASK NEW PEOPLE TO SHARE THEIR TOP4 SO WE CAN OFFER HELPFUL (READ: UNASKED FOR) SUGGESTIONS ABOUT OTHER THINGS THEY MIGHT LIKE.
                HAIL AND WELCOME TO VALHALLA WHERE WE TALK ABOUT MANY THINGS YET RARELY POWER METAL. PRAY TELL US YOUR TOP4.
                HEY HEY IT'S MONDAY MORNING SO WELCOME NEW WARRIOR AND REGALE US YOUR TOP4.
                WELCOME TO VALHALLA, WHERE NEW PEOPLE GET WELCOMED WITH EXCESSIVELY ENTHUSIASTIC WALLS OF TEXT! I JUST TYPED ONE OF THESE UP FOR ANOTHER NEW PERSON AND AM RAPIDLY RUNNING OUT OF EVEN FAINTLY CLEVER THINGS TO SAY SO I APOLOGIZE FOR THE WELCOMING NOT HAVING A CUSTOM JOKE IN IT. SPEAKING OF CUSTOM, HOW ABOUT YOU SHARE YOUR TOP4 WITH US?
                HAIL AND WELL MET. DID YOU KNOW THAT WE ALREADY HAD A? BECAUSE I DIDN'T AND WE HAVE A FIRM ONE STEVE RULE HERE. SO I GUESS THAT YOU TWO ARE GOING TO HAVE TO FIGHT TO THE DEATH SO THAT THERE IS ONLY ONE LEFT. BUT BEFORE YOU TWO GO AND TRY TO KILL EACH OTHER LIKE CIVILIZED GENTLEBEINGS, CAN WE HAVE YOUR TOP4?
                HAIL FELLOW TRAVELLER, YOU ARE CERTAINLY A WANTED GUEST IN OUR MEAD HALL. CRY HAVOC AND LET LOOSE UPON US YOUR TOP4.
                BEHOLD! HAS GRACED US WITH THEIR GLORIOUS PRESENCE! WELCOME WARRIOR, PLEASE DISREGARD THE NSFW CHANNEL AND GRACE US WITH YOUR TOP4.
                WELCOME! JOIN US IN THE LAND OF SHITTY RECOMMENDATIONS AND HORRIBLE HUMOR! WHAT ARE YOUR TOP4.
                HAIL AND WELCOME TO VALHALLA WHERE THE KNOLLS ARE GRASSY, THE BOOK DEPOSITORIES CLEARLY DON'T PROVIDE A PROPER SHOOTING ANGLE, AND JIMMY HOFFA'S IN THE LIBRARY WITH THE LEAD PIPE. WE ALSO TALK ABOUT POWER METAL THINGS OCCASIONALLY, WHICH IS WHY WE LIKE TO ASK NEW PEOPLE FOR THEIR TOP4.
                HAIL AND WELCOME TO VALHALLA WHERE WE OFTEN ARGUE ABOUT THE INTRICACIES OF BLIND GUARDIAN SOUND MIXING. PRAY TELL US YOUR TOP4.
                HAIL User AND WELCOME TO VALHALLA WHERE WE BELIEVE IN THREE THINGS: THE METAL THAT IS TRUE, ASKING NEW PEOPLE WHAT THEIR TOP4 ARE (HINT HINT) AND PUNCHING/KICKING/BANNING NAZIS!
                WELCOME TO VALHALLA WE TALK ABOUT POWER METAL SOMETIMES HERE. WHAT ARE YOUR TOP4?
                WELCOME TO VALHALLA. WE'VE HAD A LOT OF NEW PEOPLE JOINING TODAY SO YOU'RE NOT GETTING A SUPER CREATIVE GREETING. INSTEAD I'LL JUST ASK YOU TO SHARE YOUR TOP4.
                HAIL AND WELCOME TO VALHALLA, BE CAREFUL OF OUR SECRET DOOR! PLEASE TELL THE GROUP YOUR TOP4!
                HAIL AND WELCOME TO VALHALLA! KINGS OF WAR, STORMS OF ALE, HAMMERS OF GLORY, BLACKENED BEASTS, AND/OR TONNED SABAS?
                WELCOME TO VALHALLA WHERE WE COULD CERTAINLY USE SOMEONE TO WHIP THIS PLACE INTO SHAPE. WHAT ARE YOUR TOP4?
                HAIL, MIGHTY WARRIOR IF YOU CANNOT BESTOW US WITH YOUR SONIC THE HEDGEHOG OC, THEN PLEASE GRANT US THE KNOWLEDGE OF YOUR TOP4.
                HAIL AND WELL MET. WELCOME TO VALHALLA WHERE WE ARE APPARENTLY SHARING SONIC MEMES. SORRY ABOUT THAT. WHAT ARE YOUR TOP4?
                HAIL AND WELCOME TO VALHALLA WHERE WE ALL LOVE THE ASTONISHING. PRAY TELL US YOUR TOP4.
                HAIL, MIGHTY WARRIOR, COME TO ANSWER THE CALL OF THE! PLEASE BESTOW UPON US YOUR TOP4!
                HAIL AND WELCOME TO VALHALLA WHERE WE SOMETIMES GET INTO ARGUMENTS. PRAY TELL US YOUR TOP4!
                HAIL AND WELL MET, FELLOW WARRIOR OF STEELE. REST YOUR WARRIOR'S BLADE IN OUR MEADHALL OF THE GODS AND REGALE US WITH THE EPIC SAGA OF YOUR TOP4!
                WELCOME TO VALHALLA, THE LAND OF HORRIBLE MUSIC RECS! PLEASE TELL US YOUR TOP4.
                HELLO AND WELCOME TO VALHALLA WHERE SOME OF US ARE ON A BOAT! PLEASE TELL US YOUR TOP4 SO WE CAN RECOMMEND BETTER ONES!
                WELCOME TO VALHALLA, THE LAND OF HORRIBLE MUSIC RECS! PLEASE TELL US YOUR TOP4.
                WELCOME TO VALHALLA WHERE WE ARE CURRENTLY TAKLING ABOUT TATTOOS; MEETING PEOPLE IN NIGHTCLUBS AND SERVER NAMES: PRAY TELL YOUR TOP4 SO WE CAN RECOMMEND SOMETHING BETTER.
                WELCOME TO VALHALLA WHERE WE ARE ALWAYS FJORDING FOR THE PINES. I KNOW THAT'S NOT REALLY A GOOD PUN ON YOUR NAME BUT I DIDN'T HAVE A LOT TO WORK WITH AND I FIGURED LATIN FOR SOMETHING SOMETHING WILLOW TREE WAS GOOD ENOUGH. ANYWAY, WHAT ARE YOUR TOP4?
                WELCOME TO VALHALLA THE LAND OF SOMETHING OR ANOTHER WHERE WE DO FANCY THINGS THAT I'M TOO LAZY TO MAKE A DUMB JOKE ABOUT HERE. WHAT ARE YOUR TOP4 AND WHY ARE THEY ALL WARKINGS?
                HAIL AND WELCOME TO VALHALLA, LAND OF TRUTH AND HONESTY AND AUTHENTICITY AND, UH, PROBABLY BEST JUST TO MOVE ALONG. WHAT ARE YOUR TOP4?
                VALHALLELUJA WHERE WE DRINK AS MUCH BEER AS POSSIBLE AND HAVE NO HANGOVERS. PLEASE TELL THE GROUP YOUR TOP4 AND WE WILL THEN RESULT TO JUDGE YOU.
                VALHALLELUJA AND WELCOME TO THE PALACE OF THE GODS WHERE METAL REIGNS ETERNAL. ENLIGHTEN US WITH YOUR TOP4 SO WE TOO MAY STAND IN AWE OF THEIR MUSIC. 
                HAIL AND WELL MET, MIGHTY WARRIOR, THE HEAVENS TREMBLE AT YOUR ARRIVAL! PLEASE BESTOW UPON US YOUR TOP4.
                HAIL! WE OPEN THE GATES OF VALHALLA TO YOU! PLEASE BLESS US WITH YOUR TOP4 SO WE CAN RECOMMEND YOU GLORIOUS MUSIC!
                WELCOME TO VALHALLA, THIS IS NOT QUITE THE LAND OF SECRET AGENTS AND COVERT MISSIONS THAT YOU'RE USED TO, IN FACT THE ONLY SECRET THING HERE IS THE DOOR, AND YOUR ONLY MISSION IS TO PROVIDE US YOUR TOP4, THAT RELIEVE YOU FROM YOUR DAILY GRIND AT THE NERD HERD.
                HAIL AND WELL MET. I'M GOING TO CHOOSE TO ASSUME THAT YOU'RE THE PHILIP WHO JUST LEFT AND DID SO ACCIDENTALLY, POSSIBLY BECAUSE YOU HAVE A CAT WHO WAS 'HELPING' YOU WITH YOUR PHONE AND/OR COMPUTER. IF THAT IS THE CASE, THEN IN ADDITION TO THE USUAL REQUEST FOR YOUR TOP4 THAT ALL NEWCOMERS GET.
                HAIL AND WELL MET! WELCOME TO VALHALLA THE LAND OF MUSIC FANS, MUSICIANS, DRUMMERS, AND A FEW PEOPLE WE DON'T LIKE TO TALK ABOUT. WHAT ARE YOUR TOP4?
                HAIL AND WELL MET, TRAVELLER. WELCOME TO VALHALLA. UNFURL THE EPIC TALE OF YOUR TOP4.
                HAIL AND WELCOME TO VALHALLA WHERE YOU SOMETIMES TALK ABOUT MUSIC. PREY TELL YOUR TOP4 TO THE GROUP.
                VALHALLELUJA AND WELCOME TO THE HALLS OF METAL, WHERE ONLY THOSE OF THE MOST DISCERNING TASTE CAN CALL HOME. PROVE YOUR WORTHINESS BY LISTING YOUR TOP4 IN ANY ORDER YOU DEEM FIT.
                HAIL AND WELL MET! WELCOME TO THE GILDED HALLS OF VALHALLA, WHERE ENTRANCE IS GRANTED ONLY TO THOSE WITH QUESTIONABLE TASTE IN METAL. TELL US OF YOUR TOP4 SO WE TOO CAN JUDGE YOUR WORTHINESS.
                HAIL AND WELL MET. WELCOME TO VALHALLA WHERE THE WILD WOLFS AWOO LIKE IT'S STILL 2020 AND SEVEN SPIRES JUST DROPPED THEIR ÅWØØTY. WHAT ARE YOUR TOP4? 
                HAIL AND WELL MET! YOU HAVE GRACED THE GLORIOUS HALLS OF VALHALLA. PRAY TELL YOUR FELLOW WARRIORS THE TALE OF YOUR TOP4! SYMPHONIC IS GOOD TOO!
                WELCOME TO VALHALLA THERE ARE LOTS OF PEOPLE HERE WHO LIKE TO TALK ABOUT SYMPHONIC METAL, PROG METAL, ATMOBLACK, POP, AND EVEN SOMETIMES POWER METAL. CARE TO SHARE YOUR TOP4?
                HAIL AND WELL MET! WELCOME TO THE GILDED HALLS OF VALHALLA WHERE ONLY THOSE WITH THE MOST QUESTIONABLE OF MUSIC TASTE CALL HOME. MAKE HASTE AND INFORM YOUR FELLOW WARRIORS OF YOUR TOP4 SO THAT WE MAY DEEM YOU HAVE ALWAYS BEEN WORTHY.
                HAIL AND WELL MET! WELCOME TO VALHALLA WHERE THE VALKYRIES FLY AND MEAD FLOWS AND WHERE ALL THE PEOPLE POOP, NOBODY KNOWS. WHAT ARE YOUR TOP4?
                OH MY GOD ITS COME TO CLAIM OUR SOULS. PLEASE OH DARK ONE BEFORE YOU DRAG US TO THE PITS OF HELL, ENLIGHTEN ME TO THE TOP4 THAT AWAIT ME!
                HAIL AND WELCOME TO VALHALLA WHERE EAGLES FLY AND WE SOMETIMES TALK ABOUT POWER METAL BUT MOSTLY JUST HANG OUT. WHAT ARE YOUR TOP4?
                WELCOME TO VALHALLA LAND OF QUESTIONABLE FANFIC SPECULATION AND MIGHTY RIFFS. MOSTLY THE FIRST ONE THOUGH. WHAT ARE YOUR TOP4?
                HAIL YOUR MAJESTY TO THE VALIANT HALLS OF VALHALLA. WE WELCOME YOU AMONG US GODS OF DEBAUCHERY AND REQUEST YOUR TOP4 SUCH THAT WE MAY CAST JUDGEMENT.
                WELCOME TO VALHALLA. I AM NEITHER THE WALRUS NOR THE EGG-MAN, BUT I AM ASKING WHAT YOUR TOP4 ARE.
                WELCOME TO VALHALLA! UNFORTUNATELY YOU WON'T FIND ANY UNICORNS OR LEPRECHAUNS HERE, BUT YOU WILL FIND A HORDE OF METALHEADS ASKING FOR YOUR TOP4!
                WELCOME TO THE LAND OF WIZARDS AND DONKEYS WITH LASER BEAMS ATTACHED TO THEIR BUTTS. DUE TO THE FACT THAT YOU'VE JOINED SIMULTANEOUSLY, YOU MUST FIGHT IT OUT TO THE DEATH BY EACH NAMING YOUR TOP4, THE WINNER DOESN'T GET SHIT, APART FROM OUR JUDGEMENT OF YOUR TASTE OF COURSE!
                GREETINGS AND WELCOME TO THE MAJESTIC KINGDOM OF THE POWER OF METAL. NAME YOUR TOP4 WITHOUT DOUBT OR BE CAST FROM THIS REALM FOREVER!
                WELCOME TO VALHALLA WHERE WE ARE CURRENTLY TALKING ABOUT TERRIBLE MUSIC BECAUSE I AM A BAD PERSON. PLEASE DISTRACT US BY SHARING YOUR TOP4.
                HAIL AND WELCOME TO THIS IS VALHALLA, NOT THAT OTHER PLACE, BUT WE STILL HAVE SUNNY DAYS AND SWEEPING THE CLOUDS AWAY. NOW BEFORE WE GET TO WHERE THE AIR IS SWEET, CAN YOU TELL US HOW TO GET TO SESAME STREET YOUR TOP4?
                WELCOME TO THE LAND OF THE FREE, WHERE WE ALL TAKE A RAZORBLADE SIGH AT TERRIBLE RECS AND MOCK DRAMA QUEENS THAT THINK EVERY UPSETTING PIECE OF NEWS IS ARMAGEDDON. PLEASE TELL US YOUR TOP4.
                SWORDS, SHIELDS, FLAMETHROWERS, DARK MAGIC, AND YOUR TOP4, THESE ARE THE THINGS THAT WILL HELP ERADICATE THIS WORLD OF INSOLENT FANBOY OPINIONS, WILL YOU AID US IN THE GOOD FIGHT?
                WELCOME TO THE VOID WHERE YOUR TASTE IN METAL MUSIC COMES TO DIE, THOUGH DO NOT BE AFRAID, FOR YOU CAN PROVIDE US SOME LIGHT IN THIS DARK WASTELAND BY BESTOWING UPON US YOUR TOP4.
                HAIL AND WELL MET, MIGHTY WARRIOR, COME TO DELIVER SALVATION IN THESE TIMES OF TURMOIL! PLEASE BESTOW UPON US YOUR TOP4
                HAIL AND WELL MET! YOU HAVE JOINED THE REALM OF MIGHTY, GLORY, AND POP MUSIC. MAKE HASTE AND REGALE US THE TALE OF YOUR TOP4.
                WELCOME TO VALHALLA. THE PLACE WHERE POWER METAL IS DISCUSSED ALONG WITH MANY OTHER FORMS OF METAL AND POWER OR WHATEVER ELSE WE FEEL LIKE CHATTING ABOUT AT ANY GIVEN TIME. WHAT ARE YOUR TOP4?
                WELCOME TO THE LAND WHERE POWER METAL FANS COME TO LOSE THEIR FANDOM OF POWER METAL. SERIOUSLY. NOONE LIKES POWER METAL HERE. BUT GO AHEAD, WHAT ARE YOUR TOP4?
                TOP4 OR I'LL PUNCH A CAT!
                HAIL AND WELL MET. LET NOT THE FEAR OF FIRST ENCOUNTERS GRIP YOUR HEART FOR YOU ARE AMONGST BROTHERS IN THE HALLS OF VALHALLA. BLESS US WITH YOUR TOP4 SO THAT WE MAY KNOW YOUR TRUE STEEL HEART!
                HAIL AND WELL MATE FARE WARRION AND WELCOME TO VALHALLA. PULL UP A CHAIR AND REGALE US OF YOUR GLORIOUS TALES OF GLORY AND BESTOW UPON US THE KNOWLEDGE OF YOUR TOP4.
                HAIL AND WELL MET AND WELCOME TO THE AFTERLIFE. HERE WE LIKE BEER AND SHITTING ON PEOPLES TASTES SINCE WE ALL HATE POWER METAL AS IS RIGHT. SO TELL US WARRIOR OF YOUR TOP4 SO WE MAY SHIT ON YOUR TASTE TOO AND YOU MAY BECOME ONE OF US.
                LO BROTHER OF STEEL, YOUR JOURNEY HAS LEAD YOU TO A TRULEY CURSED LOCATION ON THE INTERNET! THERE SEEMS TO BE AN EXIT ILLUMINATED IN DULL EMERALD HUES, THE RUNES SPELLING OUT A MESSAGE! THEY SEEM TO SAY
                HAIL AND WELL MET AND WELCOME TO THE END OF DAYS WHICH WE CALL VALHALLA. WE HATE ALL MUSIC HERE ESPECIALLY POWER METAL. SO TELL US, MIGHTY WARRIOR, DURING YOUR PITIFUL LIFE WHICH TOP4 DID YOU PERFORM YOUR PATHETIC DEEDS TO?
                WELCOME TO VALHALLA. THIS IS A PLACE WHERE WE TALK ABOUT POWER METAL AND NEVER EVER ABOUT OTHER THINGS IN LIFE WE ENJOY LIKE BOOKS OR EUROVISION. PLEASE SHARE YOUR TOP4. AND WHATEVER YOU DO, PAY NO ATTENTION TO THE MAN BEHIND THE CURTAIN!
                BEHOLD AND WELCOME BRAVE WARRIOR. WELCOME TO THE LAND BENEATH THE ICE CAVES FULL TO THE BRIM WITH HELLFRIENDS AND DEMON BITCHES. NAME YOUR TOP4.
                HAIL AND WELCOME TO VALHALLA, THE HOME OF MOST POWERFUL POWER METAL! TO PASS THE VALKYRIES GUARDING THE HALL OF THE MOUNTAIN KING, YOU MUST DISCLOSE YOUR TOP4!
                GREETINGS MIGHTY WARRIOR, WELCOME TO THE LAND OF GLORIOUS BATTLES AND EPIC SLAYING OF EVIL, PLEASE BESTOW UPON US YOUR TOP4.
                GREETINGS AND HAIL BRAVE WARRIOR. WELCOME TO THE LAND WHERE WE SHIT ON NIGHTWISH AND SHILL WARKINGS. WHAT ATE YOUR TOP4.
                BEHOLD AND WELCOME FAIR WARRIOR TO VALHALLA. MAY YOUR ALE STAY COLD AND YOUR TASTE STAY TRVE. NAME YOUR TOP4.
                HELLO AND WELCOME TRVE WARRIOR. WELCOME TO THE LAND OF AOTY AND THE RAMPANT INFATUATION WITH FACTUALLY SHIT ALBUMS. WHAT ARE YOUR TOP4 SO THAT WE MAY JUDGE YOU FOREVER. NO PRESSURE!
                I KNOW YOU MAY ONLY BE FORGED OF IRON, BUT YOUR HEART IS FORGED OF STEEL! WHAT ARE YOUR TOP4 OF STEEL TO PROVE THE QUALITY OF YOUR FORGING?
                HAIL AND WELCOME TO THE HALLOWED HALLS OF VALHALLA! THE SKALDS NEED INSPIRATION FOR THEIR LATEST EPIC TALES, PLEASE PROVIDE IT BY TELLING THEM YOUR TOP4!
                HAIL AND WELL MET! BEFORE CALAMITY BEFALLS US ALL, QUICK! RECITE YOUR TOP4 SO THAT WE MAY GATHER THEIR POWER TO AVERT DISASTER!
                BEHOLD AND WELCOME TO VALHALLA. THE LAND WHERE CHIMPS PRAISE MANOWAR AND EVERYONE ELSE LISTENS TO MUSIC. NAME YOUR TOP4.
                VALHALLELUJA AND WELCOME TO THE HALLS OF ODIN, WHERE ONLY THOSE WITH THE MOST QUESTIONABLE EXQUISITE TASTE IN POWER METAL RESIDE. SHARE WITH US YOUR TOP4 IN WHATEVER ORDER YOU SO CHOOSE SO WE TOO MAY KNOW YOUR TASTES.
                VALHALLELUJA AND WELCOME TO THE HALLS OF ODIN WHERE POWER METAL REIGNS SUPREME. BESTOW UPON US YOUR TOP4 SO WE TOO MAY BASK IN THEIR GLORY.
            `
        });


        result = result.replace(":emeraldsword:", client.emojis.find(emoji => emoji.name === "emeraldsword"));

        if (result.includes("TOP4") === false) {
            var result_top_4 = "";
            while (result_top_4.includes("TOP4") === false) {
                result_top_4 = generator.generate({
                    wordsCount: _rand_range(20, 40),
                    sampleSize: _rand_range(3, 5),
                    source: top_4_feed
                });
            }

            result = result + "\n" + result_top_4
        }

        result = result.replace("TOP4", rand_top_4_text[Math.floor(Math.random() * rand_top_4_text.length)]);
        result = result.replace("TOP4", rand_top_4_text[Math.floor(Math.random() * rand_top_4_text.length)]);

        receivedCommand.channel.send(result);
    },
}

function _rand_range(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min)
}

function _get_user_from_mention(client, mention) {
	if (!mention) return;

	if (mention.startsWith('<@') && mention.endsWith('>')) {
		mention = mention.slice(2, -1);

		if (mention.startsWith('!')) {
			mention = mention.slice(1);
        }
        
        const user = client.users.find(user => user.id === mention);
        var name = user.nickname;
        if (name === undefined) {
            name = user.username;
        }

        return name;
	}
}
